// Conceptos de gasto por defecto (los de la planilla) y su categoría, según los bloques de la hoja TOTALES.
export type ExpenseCategory = "VARIABLE" | "ESTRUCTURA" | "INVERSION" | "REPOSICION";

export const CONCEPT_CATEGORY: Record<string, ExpenseCategory> = {
  "HOJA DE AFEITAR": "VARIABLE",
  CUELLOS: "VARIABLE",
  GUANTES: "VARIABLE",
  FARMACIA: "VARIABLE",
  DESINFECTANTE: "VARIABLE",
  LIMPIEZA: "VARIABLE",
  ACEITE: "VARIABLE",
  ALQUILER: "ESTRUCTURA",
  LUZ: "ESTRUCTURA",
  INTERNET: "ESTRUCTURA",
  MUNICIPAL: "ESTRUCTURA",
  "INGRESOS BRUTOS": "ESTRUCTURA",
  MONOTRIBUTO: "ESTRUCTURA",
  "FONDO DE COMERCIO": "ESTRUCTURA",
  GESTION: "ESTRUCTURA",
  RECEPCION: "ESTRUCTURA",
  "SOL CM": "ESTRUCTURA",
  GAS: "ESTRUCTURA",
  REPARACIONES: "ESTRUCTURA",
  TV: "INVERSION",
  ESTUFA: "INVERSION",
  "REPOSICION DE BEBIDAS": "REPOSICION",
  "COSTO CERAS": "REPOSICION",
};

